version: 2

sources:
  - name: raw
    schema: raw_data_circle 
    tables:
      - name: parcel
        identifier: raw_cc_parcel
        description: "Includes information about parcel"
        columns:
          - name: Parcel_id
            description: "Unique id of the parcel"
            tests:
              - not_null
              - unique
          - name: Transporter 
            description: "Carrier name of the parcel"
            tests:
              - not_null

      - name: parcel_product
        identifier: raw_cc_parcel_product
        description: "Product details in the parcel"
        columns:
          - name: Parcel_id
            description: "Id of the parcel"
            tests:
              - not_null